---
development:
  cloud_name: dximobcdx
  api_key: '231957412117215'
  api_secret: 8SUGI8D3G27U2s4eW_8EN1Q-PH8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dximobcdx
  api_key: '231957412117215'
  api_secret: 8SUGI8D3G27U2s4eW_8EN1Q-PH8
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dximobcdx
  api_key: '231957412117215'
  api_secret: 8SUGI8D3G27U2s4eW_8EN1Q-PH8
  enhance_image_tag: true
  static_file_support: false
